love2d/love

.gitattributes

When creating an archive, the GitHub repository and VCS-specific files
are now ignored.
The diff "hunk header" is customized for C/C++ [1].
[1]: https://git-scm.com/docs/gitattributes#_defining_a_custom_hunk_header

Create a gitattributes file

---

.github/workflows/main.yml

Note that I changed `runs-on` to Ubuntu 16.04, which might be undesired, but using latest would result in an AppImage that would be useful on way less machines.
As discussed with slime it should be fine that I am pulling a script from my pfirsich/love-appimages repository. 
Sadly the resulting artifact will be a .zip file called love.AppImage.zip that contains the AppImage, which is, for now, a restriction of the upload-artifact action: https://github.com/actions/upload-artifact/issues/3#issuecomment-598820814
See this action for an example artifact (and please verify that it works for you as well): https://github.com/pfirsich/love/actions/runs/56211949

Add GitHub action steps to build AppImage

---

src/modules/timer/Timer.cpp
src/modules/timer/Timer.h

As we have talked about a bit on the Discord server, I made getTimer relative to it's first invocation (which happens at the start of love.run), so that there are less precision issues (and also more predictable behaviour).
I did some investigation of whether, if starting from 0, floats would be enough for most tasks and according to the godbolt I shared on the server too (https://godbolt.org/z/M4HadW) it seems that even for a week of runtime, the precision is still pretty good.
I did take a minute or two to understand all the macro stuff to handle the different platforms and moved some stuff around to make it easier to understand, but I realize this could possibly be a change too big to justify the little feature impact, so if you don't like it, I can change that back.
I tested by …

Make getTime() relative to first invocation

---

src/modules/physics/box2d/Body.cpp
src/modules/physics/box2d/Body.h
src/modules/physics/box2d/wrap_Body.cpp

Allows getting/setting a body's full kinematic state in a single call. My use case is
```lua
function myentity:think()
self.x, self.y, self.a, self.dx, self.dy, self.da = self.body:getState()
...
end
```

Add Body.getKinematicState and Body.setKinematicState

---

src/modules/sound/SoundData.cpp
src/modules/sound/SoundData.h
src/modules/sound/wrap_SoundData.cpp

This pull request adds 2 functions to `SoundData` object.
```c
void SoundData:copyFrom(SoundData src, number srcStart, number count, number dstStart = 0)
SoundData SoundData:slice(number start, number length = -1)
```
`SoundData:copyFrom` works similar to [`ImageData:paste`](https://love2d.org/wiki/ImageData:paste) but operates on SoundData instead. The copy operation only works if the channel count is same along with additional range checks. Note that this function does NOT perform audio mixing nor resampling (in case of sample rate mismatch), audio sample is copied as-is, or with bit-depth conversion if needed. Ideally an additional FFI implementation is also needed but I have no idea how to call `memmove` without calling `ffi.cdef` at `wrap_SoundData.lua`.
`SoundData:slice` allows user …

SoundData:copyFrom() and SoundData:slice()

---

src/common/ios.h
src/common/ios.mm
src/modules/audio/Audio.h
src/modules/audio/null/Audio.cpp
src/modules/audio/null/Audio.h
src/modules/audio/openal/Audio.cpp
src/modules/audio/openal/Audio.h

iOS audio interruptions (eg. alarm, or phone call ringer) disable the OpenAL context. 
This code handles the interruptions and restores the OpenAL context when the interrupt ends or the application is brought to the foreground. 
NOTE: I'm not happy with adding two methods to the Audio class to pause/restore the OpenAL context. Maybe you can think of a more elegant way to do it.

adds iOS audio interruption handling and recovery

---

src/modules/graphics/opengl/OpenGL.cpp
src/modules/graphics/wrap_GraphicsShader.lua

The Nvidia Tegra 3 driver for Android (used by Ouya) erroneously claims
to support the desktop-oriented GL_EXT_texture_array extension. On
desktop GPUs using (non ES) OpenGL, the glTexImage3D and similar
functions are always present, and the GL_EXT_texture_array extension
simply adds support for texture arrays to those functions. On OpenGL ES
2.0, those functions do not exist, and GL_OES_texture_3D is required to
define them.
Calling glTexImage3D on the Tegra 3 causes a segfault. This change works
around the issue by manually setting GLAD_EXT_texture_array to 0 on
OpenGL ES 2.0 systems, which causes LÖVE to avoid codepaths that assume
that the 3D texture functions are available. It doesn't make sense for
any OpenGL ES 2.0 GPU to claim support for GL_EXT_texture_array.
Fixes #1647

Disable GL_EXT_texture_array on OpenGL ES 2.0

---

src/modules/physics/box2d/Body.cpp
src/modules/physics/box2d/Body.h
src/modules/physics/box2d/wrap_Body.cpp

This is identical to `Body:getWorldPoints`, except it gets the local points instead.
Fixes #1614.
I've tested this by getting 4 points in each corner around the cursor, converting those points to local points, converting those local points back into world points, and checking that the points are equal. Then using those points to draw a polygon (a square) around the cursor.
<details><summary>Lua script</summary>
```lua
local world, body
function love.load()
love.graphics.setBackgroundColor(0, 255, 255)
love.physics.setMeter(64)
world = love.physics.newWorld()
local width, height = love.window.getMode()
body = love.physics.newBody(world, width/2, height/2)
end
function love.update(dt)
world:update(dt)
end
function love.draw()
love.graphics.setLineWidth(12)
-- Build coordinates for squares …
```

Fix #1614: add Body:getLocalPoints

---

src/modules/graphics/opengl/Graphics.cpp

Saw `setDefaultStorageBuffer` was never getting called, noticed this, appears to be a typo, opened this PR.

Fix default shader storage buffer initialization;

---

src/modules/physics/box2d/RevoluteJoint.cpp
src/modules/physics/box2d/RevoluteJoint.h
src/modules/physics/box2d/wrap_RevoluteJoint.cpp

Getting `dt` from `Timer` if not provided in the call is not as straightforward as I thought (not a static method), and I don't want to fuck up my first commit in this codebase by doing something stupid.
Issue #1731

use dt instead of inv_dt in RevoluteJoint::getMotorTorque

---

src/common/runtime.cpp
src/libraries/luasocket/libluasocket/ftp.lua.h
src/libraries/luasocket/libluasocket/headers.lua.h
src/libraries/luasocket/libluasocket/http.lua.h
src/libraries/luasocket/libluasocket/ltn12.lua.h
src/libraries/luasocket/libluasocket/mbox.lua.h
src/libraries/luasocket/libluasocket/mime.lua.h
src/libraries/luasocket/libluasocket/smtp.lua.h
src/libraries/luasocket/libluasocket/socket.lua.h
src/libraries/luasocket/libluasocket/tp.lua.h
src/libraries/luasocket/libluasocket/url.lua.h
src/modules/event/wrap_Event.cpp
src/modules/graphics/wrap_Graphics.cpp
src/modules/graphics/wrap_Video.cpp
src/modules/love/love.cpp
src/modules/math/wrap_Math.cpp

LOVE's embedded script now shows as `[love "filename.lua"]` and LuaSocket's embedded script shows as `[socket "filename.lua"]`.
Fixes #1748.

Change luaL_loadbuffer chunkname with prefixes.

---

src/modules/filesystem/wrap_Filesystem.cpp

`love.filesystem.newFileData` only accepts `string` as source data. This can be an issue with large data sizes due to LuaJIT's memory limits. With this change `newFileData` can be called with `ByteData` (or any other `Data` object).

Create FileData from Data objects

---

src/modules/system/System.cpp

see [1786](https://github.com/love2d/love/issues/1786)
error: cast from 'HINSTANCE' {aka 'HINSTANCE__*'} to 'int' loses precision [-fpermissive]

Windows: Fix compile error loses precision

---

src/modules/filesystem/wrap_Filesystem.cpp

As discussed in #1773, it's probably a good idea to show a warning about usage of slashes in `require`, then evalue when to enforce this by throwing Lua error.

Show deprecation notice when slashes is passed to require.

---

src/modules/audio/Audio.cpp
src/modules/audio/Audio.h
src/modules/audio/null/Audio.cpp
src/modules/audio/null/Audio.h
src/modules/audio/openal/Audio.cpp
src/modules/audio/openal/Audio.h
src/modules/audio/openal/Pool.cpp
src/modules/audio/openal/Pool.h
src/modules/audio/wrap_Audio.cpp
src/modules/love/callbacks.lua

A simpler approach to #1804. Fixes #1537 _completely_.
This pull request adds several features:
* `love.audio.getPlaybackDevice()` function get current playback device name.
* `love.audio.getPlaybackDevices()` function retrieves all available playback devices in a Lua table.
* `love.audio.setPlaybackDevice(name)` function re-set the output device to `name`. `name` can be `nil` (for automatic default) or a string returned from `love.audio.getPlaybackDevices()` function above. Returns `true` on success or `false` and error message on failure.
* `love.audiodisconnected` callback when the audio device is disconnected and must be reconnected with `love.audio.setPlaybackDevice()`.
Now here are some notes:
* `love.audio.setPlaybackDevice()` is only supported if …

Support for Audio Device Selection and Disconnection Callback

---

changes.txt
src/modules/physics/box2d/World.cpp
src/modules/physics/box2d/World.h
src/modules/physics/box2d/wrap_World.cpp

[Quality of life]
I find writing the callback to get all the fixtures in an area a hassle, I just want a list of them.
This is a quality of life more than anything else, instead of this:
```lua
local fixtures = {}
local callback = function(fixture)
table.insert(fixtures, fixture)
return true
end
world:queryBoundingBox(-500, -500, 500, 500, callback)
print(#fixtures)
```
You can do just 
```lua
local fixtures = world:getFixturesInArea(-500, -500, 500, 500)
print(#fixtures)
```
Because there is less indirection, it has a modest performance improvement compared to the callback method:
Measured in debug build, total time 10,000 calls, on an area with 100 fixtures:
And the same test in Release build:
So its maybe 1.35x faster or so.

Added World:getFixturesInArea()

---

src/modules/graphics/Polyline.cpp

Resolves https://github.com/love2d/love/issues/1760
The drawing was having these NAN normals inserted, because the segment length was 0.
This adds asserts to check the normals are never NAN, and early return to skip the line segment if the length is 0.
-------------------------------------------
Before, using this in Love2d:
```lua
love.graphics.line(0, 0, 50, 50, 50, 50, 100, 100)
```
Results in the line draw normals looking like this:
Which through some mechanism, doesn't crash, but doesn't draw the line either (points drawn for debug):
With the skipping of length 0 segments, the normals will look valid, and the line will draw as expected:
-----------------------------------
Duplicate points don't seem to cause any problem with the "none" and "bevel" join styles, so I didn't worry about …

FIx polyline adding NaN normals, which breaks the line rendering

---

changes.txt
src/modules/filesystem/Filesystem.cpp
src/modules/filesystem/Filesystem.h
src/modules/filesystem/wrap_Filesystem.cpp

This adds optional `loadMode` parameter to `love.filesystem.load(path, loadMode)`. `loadMode` can be `"b"` to only accept binary chunk, `"t"` to only accept text chunk, or `"bt"` for both. `"bt"` is the default behavior if not specified. Fixes #1849
Note that this effectively prevents people who trying to switch between Lua 5.1 and LuaJIT in Windows by replacing the DLL. If this is undesired please let me know so I can think of another approach.

Add optional load mode parameter to love.filesystem.load.

---

src/libraries/noise1234/noise1234.cpp
src/libraries/noise1234/noise1234.h
src/libraries/noise1234/simplexnoise1234.cpp
src/libraries/noise1234/simplexnoise1234.h
src/modules/math/MathModule.h
src/modules/math/wrap_Math.cpp
src/modules/math/wrap_Math.lua

As per Discord discussion, patent of 3D and 4D simplex noise is no longer a concern (#1002). This pull request adds 2 functions and deprecate 1 function.
* `love.math.perlinNoise(x[, y[, z[, w]]])` which generates 1D-4D Perlin Noise
* `love.math.simplexNoise(x[, y[, z[, w]]])` which generates 1D-4D Simplex Noise
* Deprecate `love.math.noise` to prevent confusion.
There was a few ideas on how to specify the noise function, but I found out separating it to 2 functions is the best approach in terms of speed. The other proposal was to use `love.math.noise(noiseType, x[, y[, z[, w]]])` but this has some performance overhead on non-JIT-ed environments.

Separate love.math.noise to perlinNoise and simplexNoise

---

src/love.cpp
src/modules/love/boot.lua

Hi, I wanted to prepare a PR for #1735, does something like this look ok?
I added a `--help` option in the same way as there is `--version` now. It's used only when it's before a game dir or a love file, otherwise it's passed to the game arguments, example:
```
love --help #prints usage
love path/to/game --help #passed to the game
love game.love --help #passed to the game
```
I also printed usage when there is "no game" displayed, is that ok?
Could someone please check my English in the usage message (or propose a completely different wording?)
Is there a place where to put the string and use it on both places (see the diff)?
Thanks

print usage when there is no game and when --help option is used

---

src/modules/physics/box2d/DistanceJoint.cpp
src/modules/physics/box2d/DistanceJoint.h
src/modules/physics/box2d/MouseJoint.cpp
src/modules/physics/box2d/Physics.cpp
src/modules/physics/box2d/Physics.h
src/modules/physics/box2d/WeldJoint.cpp
src/modules/physics/box2d/WeldJoint.h
src/modules/physics/box2d/WheelJoint.cpp
src/modules/physics/box2d/WheelJoint.h
src/modules/physics/box2d/wrap_DistanceJoint.cpp
src/modules/physics/box2d/wrap_MouseJoint.cpp
src/modules/physics/box2d/wrap_Physics.cpp
src/modules/physics/box2d/wrap_WeldJoint.cpp
src/modules/physics/box2d/wrap_WheelJoint.cpp

As it says on the tin, this is two commits to fix the behaviour in #1834. The first fixes it with minimal changes (by setting the default values from before), and the second is a draft of a more significant change
[Box2d 2.4.0 converted all its joints to use stiffness and damping](https://github.com/erincatto/box2d/blob/main/CHANGELOG.md#dynamics), rather than the old spring-damper, which meant that the springy-ness is defined by `stiffness`, rather than `frequency`. They provided a helper function for linear and angular stiffness to convert from the old way to the new way
When https://github.com/love2d/love/pull/1613 was merged, thegrb93 helpfully added in some conversion steps to continue taking the frequency/damping values, and under the hood use the helper functions to convert them to …

Fix #1834: Give MouseJoint a sensible stiffness and damping initial value

---

src/modules/love/callbacks.lua

As it says on the tin.
`love.graphics.setNewFont` is deprecated.
Before:
After:

fix: remove usage of setNewFont on error handler

---

CMakeLists.txt
platform/unix/deps.m4
src/modules/event/sdl/Event.cpp
src/modules/joystick/sdl/Joystick.cpp
src/modules/window/sdl/Window.cpp

Historically LOVE only requires at least SDL 2.0.0 to build, forcing new functionality that require certain SDL versions to be kept around `SDL_VERSION_ATLEAST` macro. However, this makes LOVE build crippled when someone compiles with older SDL.
Furthermore with the addition of the `love.sensor` module (#1873), we have to trade between requiring at least certain SDL version or lacking `love.sensor` module completely in their LOVE build.
After some discussion in Discord, it's been agreed to bump required LOVE minimum SDL version to 2.0.9. This PR cleanup some `SDL_VERSION_ATLEAST` macro, up to SDL 2.0.9.
I also clean up the touch coordinate normalization workaround code in Linux as I don't think it's needed anymore. I checked the original issue (libsdl-org/SDL#2656) and it's been fixed …

Bump minimum SDL version to 2.0.9

---

src/modules/graphics/opengl/OpenGL.cpp

Silence warnings against sprintf in OpenGL module. Acceptable since compilers used for love 12 have snprintf.

Prefer snprintf over sprintf in OpenGL

---

platform/unix/configure.ac
src/common/config.h

This also benefits main branch so I'm targetting main branch instead of 12.0.

Compile with hidden symbol visibility by default.

---

src/modules/graphics/wrap_Canvas.cpp

In many cases, `Canvas:renderTo` would have been much more useful to me if it could accept additional parameters - without them, you're forced to make a new function if you want it to do something slightly different.
Accepting varargs can let you make the same function do different things without having to create a new one, which can save on a lot of garbage creation.

Allow Canvas:renderTo to accept varargs

---

.github/workflows/main.yml

Closes #1891.
To test out if it works:
1. Download the PDBs and put it beside the LOVE executables.
2. Run LOVE (love.exe or lovec.exe) through WinDBG/Visual Studio debugger that run a script which 100% crashes LOVE (i.e. calling `luaopen_love` with NULL `L` through FFI).
I use this script as demonstration.
```lua
local ffi = require("ffi")
local liblove = ffi.load("liblove.dll")
ffi.cdef[[
int luaopen_love(void*)
]]
liblove.luaopen_love(nil)
```
Note that this effectively change the executable name of the LOVE DLL from `love.dll` to `liblove.dll`.

Provide PDB with Source Indexing as Artifacts

---

src/modules/graphics/Polyline.cpp

Fixes #1894.
Correctly handles the case where a line doubles back on itself. For both miter and bevel, the line will be drawn like this (angle increased for readability; in reality the angle pqr would be much smaller of course)
Because the normal flips here, the triangle strip would twist. So to draw this we "contain" the twist in an invisible zero-size quad
Here's an example showing the importance of the twist correction
```lua
function love.draw()
love.graphics.setLineWidth(20)
love.graphics.setLineJoin("miter")
love.graphics.line({
190, 200,
200, 200,
100, 200
})
love.graphics.setLineJoin("bevel")
love.graphics.line({
100, 300,
200, 300,
190, 300
})
end
```

graphics: fix for anti-parallel line segments

---

changes.txt
src/libraries/enet/enet.cpp

Was #1791 but rewritten to exclude the include of `love::data` by using light userdata and a size
This adds the following variants for `peer:send` and `host:broadcast` while preserving the previous function arguments
`peer:send(light userdata pointer, number size, [number channel, [string flag]])`
`host:broadcast(light userdata pointer, number size, [number channel, [string flag]])`
Working example
```lua
-- client
local enet = require("enet")
local host = enet.host_create()
local server = host:connect("localhost:10001", 64, 0)
host:service(100)
-- populate byteData
local byteData = love.data.newByteData(5)
local ffi = require("ffi")
local ptr = ffi.cast("void*", byteData:getFFIPointer())
ffi.copy(ptr, "hello")
server:send(byteData:getPointer(), byteData:getSize(), 11, "reliable") -- send …
```

Added variants for peer:send and host:broadcast which accepts light userdata and size

---

CMakeLists.txt
src/modules/filesystem/physfs/Filesystem.cpp
src/modules/filesystem/physfs/PhysfsIo.cpp
src/modules/filesystem/physfs/PhysfsIo.h

When a fused löve executable is signed with codesign on Windows some data is appended to the executable, preventing physfs from finding the zip file at the end of the file.
To help physfs out a bit, we try to find the zip ourselves in the case of regular mount failure by looking for it's characteristic end of central directory record and, once found, pretend to physfs that the file is shorter than it actually is and ends at the end of the zip file.
------
This is another one of those PRs that don't try to say "please merge", but rather a "do you possibly want this?". 
There were questions on the Discord about issues with loading fused, signed Windows executables. I thought it's possible to do this with a custom PHYSFS_Io, so I did it. It seemed like there were other people possibly …

Add PHYSFS_Io StripSuffixIo to skip codesign signatures

---

src/modules/graphics/vulkan/Graphics.cpp
src/modules/graphics/vulkan/Graphics.h
src/modules/graphics/vulkan/Shader.cpp
src/modules/graphics/vulkan/Shader.h
src/modules/graphics/vulkan/Vulkan.cpp
src/modules/sound/lullaby/MP3Decoder.cpp

Just a few things I have found and improved:
- Running löve under RenderDoc doesn't crash anymore
- Running löve with an android emulator uses right gamma correction
- Running g3d example works correctly (although y axis flipped)
- Handling of descriptor pools / sets in Shader.h/.cpp has been simplified
- Vulkan::cmdTransitionImageLayout has been changed to be more maintainable

vk: maintenance

---

src/modules/graphics/wrap_Graphics.lua

Quite self-explanatory
Games from previous versions using deprecated stencil functions will most likely not working as intended
```lua
love.graphics.stencil(stencil, "replace", 1, false)
love.graphics.setStencilTest("greater", 0)
```
Example above vice versa would work the same in previous love2d version games but since currently stencil function resets the properties it wouldnt work the same
This pr fixes it

Fix deprecated love.graphics.stencil function resetting stencilMode

---

testing/tests/sensor.lua

This will test more `love.sensor` functions if hardware accelerometer or gyroscope is available (such as in iOS, Android, or in laptops with such sensors). Note that the tests will be skipped if no accelerometer and gyroscope is available.
The tests passed in my laptop which have both sensors. I didn't write tests for `love.sensor.setEnabled` as `love.sensor.isEnabled` also performs `setEnabled` test.
```
love.conf
--modules "sensor"
love.sensor.testmodule.start
love.sensor.getData()                     ==> PASS - 0.026s (10/10)
love.sensor.getName()                     ==> PASS - 0.015s (6/6)
love.sensor.hasSensor()                   ==> PASS - 0.017s (2/2)
love.sensor.isEnabled()                   ==> PASS - 0.016s (4/4)
love.sensor.testmodule.end
4 PASSED || 0 FAILED || 0 SKIPPED || …
```

Add More Tests For love.sensor.

---

src/common/runtime.cpp

Closes #1946
Since love already handles double free-like cases for `release` using `Proxy`, this was as simple as calling `release`. Or technically, registering `__close` as an alias for `release`.
To test this I added some extra patches:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ce94ff61..fac9d552 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -223,7 +223,7 @@ Please see https://github.com/love2d/megasource
set(LOVE_LUA_LIBRARY ${LUAJIT_LIBRARY})
set(LOVE_LUA_INCLUDE_DIR ${LUAJIT_INCLUDE_DIR})
else()
-               find_package(Lua51 REQUIRED)
+               find_package(Lua REQUIRED)
set(LOVE_LUA_LIBRARY ${LUA_LIBRARY})
set(LOVE_LUA_INCLUDE_DIR ${LUA_INCLUDE_DIR})
endif()
diff --git a/src/common/runtime.h b/src/common/runtime.h
index 747c38e8..820bd4b9 100644
--- …
```

Add support for lua 5.4 to-be-closed variables

---

CMakeLists.txt
src/modules/audio/openal/Audio.h
src/modules/audio/openal/Effect.h
src/modules/audio/openal/Filter.h
src/modules/audio/openal/Pool.h
src/modules/audio/openal/RecordingDevice.h
src/modules/audio/openal/Source.h

Here are some smaller and larger changes to CMakeLists.txt I thought of when converting the linux builds to cmake.
You're definitely welcome to pick and choose parts of this PR you'd like to merge (if any). I think all changes are net improvements, but I realize some might be controversial, especially the modules-as-targets one, with its extra dependency tracking.

Modernize cmake builds

---

CMakeLists.txt

The lovedep target is renamed from SDL2 to SDL, but the variables used are kept as-is (with SDL3 specific stuff added).
This is so that when the move to SDL3 should be made, SDL2 stuff can be removed.
The linux path is not touched, because I do not know how this should be done exactly.
This PR accompanies love2d/megasource#17

Add support for SDL3 when building with megasource

---

CMakeLists.txt

Add `-fobjc-arc` when building for love_3p_luahttps on macOS.
Fixes error: "ARC is off"
I'm aware of the warning that "CMake is not an officially supported build system for love on Apple platforms"; this is a small step toward improving it.
This PR is for the main branch. The problem also affects the 12.0-development branch but that branch has not been updated in three months and other changes in CMakeLists.txt in the main branch mean this patch would have to be changed to apply to the 12.0-development branch.
The 11.x branch is not affected because the luahttps module was not used in that branch.

Add -fobjc-arc for love_3p_luahttps on macOS

---

changes.txt

The same entry existed on two lines:
https://github.com/love2d/love/blob/2aa4e4b3ea1522961f51d44a9f01f33b1db43030/changes.txt#L85
https://github.com/love2d/love/blob/2aa4e4b3ea1522961f51d44a9f01f33b1db43030/changes.txt#L100
so I removed one.

Remove duplicate entry in changes.txt

---

CMakeLists.txt

This fixes the CMake build on macOS by fixing #2068 and working around #2066.

Fix CMake build on macOS

---

CMakeLists.txt
extra/cmake/LoveMacros.cmake

Group liblove and lovedep projects in Visual Studio

---

src/modules/data/wrap_DataModule.cpp

I got annoyed that I had to keep calculating the size lua side when making a new dataview. So, this change makes the 3rd arg [size], optional and is calculated as `love.data.newByteData` calculates the default size when calling `love.data.newByteData(someData)`  [this line](https://github.com/love2d/love/blob/main/src/modules/data/wrap_DataModule.cpp#L88)
I made this change on github directly; and so I haven't tested the change. I'll add a comment once I've tested the build to ensure it works as expected.
Example usage:
```lua
local data = love.data.newByteData(200)
local offset = 100
-- Change:
local dataview = love.data.newDataView(data, offset)
-- Previously:
local dataview = love.data.newDataView(data, offset, data:getSize() - offset)
```

Made love.data.newDataView size arg optional

---

src/modules/graphics/Polyline.cpp

I have encountered reproducible segfaults on OpenBSD's love (version 11.5)  when using it to run the game [Arco](https://arco.game/), occurring some way into the second act in the NPC party member inventory:
```
(gdb) bt
#0  0x00000111a6befa07 in love::graphics::Polyline::render(love::Vector2 const*, unsigned long, unsigned long, float, float, bool) ()
from /usr/local/lib/liblove-11.5.so.0.0
#1  0x00000111a6bda0d5 in love::graphics::Graphics::polyline(love::Vector2 const*, unsigned long) () from /usr/local/lib/liblove-11.5.so.0.0
#2  0x00000111a6c24ed4 in love::graphics::w_line(lua_State*) ()
from /usr/local/lib/liblove-11.5.so.0.0
#3  0x0000011115378146 in lj_BC_FUNCC ()
from /usr/local/lib/libluajit-5.1.so.1.0
#4  0x0000010ecd83f6d8 in ?? ()
#5  0x0000010ecd83f1db in ?? ()
#6 …
```

avoid segfault on OpenBSD by not accessing array at index -1

---

src/modules/font/GenericShaper.cpp
src/modules/font/freetype/HarfbuzzShaper.cpp
src/modules/graphics/Font.cpp

The `"justify"` align mode now looks more like proper justified text - the right edges of lines are flush with the given wrap width.
Before:
https://github.com/user-attachments/assets/1e53dca5-9276-4f87-a73d-10029ca307c4
After:
https://github.com/user-attachments/assets/5fca5614-5df9-4b70-aecd-db5043a41fab

Improve `"justify"` text alignment

---

CMakeLists.txt
extra/cmake/LoveMacros.cmake
src/modules/filesystem/NativeFile.cpp
src/modules/filesystem/NativeFile.h

This removes any platform-specific code from `NativeFile` and rely on SDL3 IO functions diretly.
One issue I found with this is that SDL3 doesn't expose any function to set the IO buffering mode. This is why this change goes into a PR to discuss how should the buffering function behaves.

Replace NativeFile to use SDL IO functions.

---

src/modules/love/boot.lua

Changing the icon to a custom one (with t.window.icon in conf.lua) results in the icon changing with a delay:
It is necessary to change the order of window setup in boot.lua: first change the icon, and then open the window:

Fixed delay in changing window icon on boot

---

CMakeLists.txt

Updated CMake minimum from 3.16 to 3.19 to address problems found by @noahwagner04 in issue #2184

Update cmake minimum version to 3.19
